global:
  workspace: ./data
  max_retries_requeued: 3
  github_credentials:
    sessions: []
    tokens: []
    strategy: round_robin
  user_agents:
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/138.0.0.0 Safari/537.36
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/138.0.0.0 Safari/537.36
  - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0
    Safari/537.36
pipeline:
  threads:
    search: 1
    gather: 8
    check: 4
    inspect: 2
  queue_sizes:
    search: 100000
    gather: 200000
    check: 500000
    inspect: 1000000
monitoring:
  update_interval: 2.0
  error_threshold: 0.1
  queue_threshold: 1000
  memory_threshold: 1073741824
  response_threshold: 5.0
display:
  contexts:
    system:
      standard:
        title: System Status
        show_workers: true
        show_alerts: true
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      compact:
        title: System Status
        show_workers: false
        show_alerts: false
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      detailed:
        title: Detailed System Status
        show_workers: true
        show_alerts: true
        show_performance: true
        show_newline_prefix: true
        width: 80
        max_alerts_per_level: 3
    monitoring:
      standard:
        title: Pipeline Monitoring
        show_workers: true
        show_alerts: true
        show_performance: true
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      detailed:
        title: Detailed Pipeline Monitoring
        show_workers: true
        show_alerts: true
        show_performance: true
        show_newline_prefix: true
        width: 80
        max_alerts_per_level: 3
    task:
      standard:
        title: Task Manager Status
        show_workers: true
        show_alerts: false
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      compact:
        title: Task Manager Status
        show_workers: false
        show_alerts: false
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
    application:
      standard:
        title: Application Status
        show_workers: false
        show_alerts: true
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      detailed:
        title: Detailed Application Status
        show_workers: true
        show_alerts: true
        show_performance: true
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
    main:
      standard:
        title: Pipeline Status
        show_workers: true
        show_alerts: false
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
persistence:
  batch_size: 50
  save_interval: 30
  queue_interval: 60
  snapshot_interval: 300
  auto_restore: true
  shutdown_timeout: 30
  simple: false
worker:
  enabled: false
  min_workers: 1
  max_workers: 10
  target_queue_size: 100
  adjustment_interval: 5.0
  scale_up_threshold: 0.8
  scale_down_threshold: 0.2
  log_recommendations: true
ratelimits:
  github_api:
    base_rate: 1.0
    burst_limit: 5
    adaptive: true
  github_web:
    base_rate: 2.0
    burst_limit: 3
    adaptive: false
tasks:
- name: openai
  enabled: true
  provider_type: openai_like
  use_api: false
  stages:
    search: true
    gather: true
    check: true
    inspect: true
  extras: {}
  api:
    base_url: https://api.openai.com
    completion_path: /v1/chat/completions
    model_path: /v1/models
    default_model: gpt-4o-mini
    auth_key: Authorization
    extra_headers: {}
    api_version: ''
    timeout: 30
    retries: 3
  patterns:
    key_pattern: sk(?:-proj)?-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}
    address_pattern: ''
    endpoint_pattern: ''
    model_pattern: ''
  conditions:
  - query: '"T3BlbkFJ"'
  rate_limit:
    base_rate: 2.0
    burst_limit: 10
    adaptive: true
