global:
  workspace: "./data"
  max_retries_requeued: 3
  github_credentials:
    sessions: []
    tokens: []
    strategy: "round_robin"
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"

pipeline:
  threads:
    search: 1
    gather: 8
    check: 12
    inspect: 3
  queue_sizes:
    search: 100000
    gather: 200000
    check: 500000
    inspect: 1000000

monitoring:
  update_interval: 2.0
  error_threshold: 0.1
  queue_threshold: 1000
  memory_threshold: 1073741824
  response_threshold: 5.0

persistence:
  batch_size: 50
  save_interval: 30
  queue_interval: 60
  snapshot_interval: 300
  auto_restore: true
  shutdown_timeout: 30
  format: txt

worker:
  enabled: true
  min_workers: 2
  max_workers: 16
  target_queue_size: 200
  adjustment_interval: 5.0
  scale_up_threshold: 0.8
  scale_down_threshold: 0.2
  log_recommendations: true

ratelimits:
  github_api:
    base_rate: 0.5
    burst_limit: 5
    adaptive: true
  github_web:
    base_rate: 0.25
    burst_limit: 2
    adaptive: true

tasks:
  - name: "gemini"
    enabled: true
    provider_type: "gemini"
    use_api: false
    stages:
      search: true
      gather: true
      check: true
      inspect: true
    api:
      base_url: https://generativelanguage.googleapis.com
      model_path: /v1/models
      completion_path: /v1/models
      default_model: gemini-2.5-pro
      auth_key: x-goog-api-key
      extra_headers:
        User-Agent: "KeyValidator/1.0 (+https://example.com)"
      api_version: ""
      timeout: 20
      retries: 5
    patterns:
      key_pattern: 'AIza[0-9A-Za-z_-]{35}'
    conditions:
      - query: '/AIza[0-9A-Za-z_-]{35}/ AND (gemini OR generativelanguage.googleapis.com)'
      - query: 'GEMINI_API_KEY OR GOOGLE_API_KEY'
      - query: 'GEMINI_API_KEY AND (filename:.env OR path:.env)'
      - query: '"x-goog-api-key" AND (gemini OR generativelanguage.googleapis.com)'
      - query: '"generativelanguage.googleapis.com" AND "AIza"'
    rate_limit:
      base_rate: 0.6
      burst_limit: 6
      adaptive: true
    extras:
      directory: "gemini"
