global:
  # 鐢ㄤ簬瀛樺偍鏁版嵁鍜岀粨鏋滅殑宸ヤ綔鐩綍
  workspace: "./data"
  # 浠诲姟澶辫触鍚庡彲閲嶆柊鎺掗槦鐨勬渶澶ф鏁?  max_retries_requeued: 3
  # GitHub鍑嵁閰嶇疆
  github_credentials:
    # GitHub浼氳瘽浠ょ墝锛堟帹鑽愪娇鐢紝浠ヨ幏寰楁洿楂樼殑閫熺巼闄愬埗锛?    # 褰?sessions/tokens 涓虹┖ [] 鎴栦粎鍖呭惈浠?your_ 寮€澶寸殑鍗犱綅鍊兼椂锛屽皢鑷姩浠庣幆澧冨彉閲忔帴绠★細
    #   - GITHUB_SESSIONS="sess_a,sess_b"
    #   - GITHUB_TOKENS="ghp_xxx,ghp_yyy"
    sessions: []
    # GitHub API浠ょ墝锛堝彲閫夛紝閫熺巼闄愬埗杈冧綆锛?    tokens: []
    # 璐熻浇鍧囪　绛栫暐锛歳ound_robin锛堣疆璇級鎴杛andom锛堥殢鏈猴級
    strategy: "round_robin"
  # Web璇锋眰鐨勭敤鎴蜂唬鐞嗗垪琛紙鑷姩杞崲锛?  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"

# 绠￠亾闃舵閰嶇疆
pipeline:
  # 姣忎釜闃舵鐨勭嚎绋嬫暟
  threads:
    search: 2 # 鎼滅储闃舵绾跨▼锛堢敱浜庨€熺巼闄愬埗锛屼繚鎸佽緝浣庯級
    gather: 8 # 閲囬泦闃舵绾跨▼
    check: 4 # 楠岃瘉闃舵绾跨▼
    inspect: 2 # API鑳藉姏妫€鏌ョ嚎绋?  # 姣忎釜闃舵鐨勯槦鍒楀ぇ灏?  queue_sizes:
    search: 200000 # 鎼滅储缁撴灉闃熷垪
    gather: 200000 # 閲囬泦浠诲姟闃熷垪
    check: 500000 # 楠岃瘉浠诲姟闃熷垪
    inspect: 1000000 # API鑳藉姏妫€鏌ヤ换鍔￠槦鍒?
# 绯荤粺鐩戞帶閰嶇疆
monitoring:
  # 鐩戞帶鏇存柊闂撮殧锛堢锛?  update_interval: 2.0
  # 閿欒鐜囬槇鍊硷紙0.0鍒?.0锛?  error_threshold: 0.1
  # 闃熷垪澶у皬璀﹀憡闃堝€?  queue_threshold: 1000
  # 鍐呭瓨浣跨敤闃堝€硷紙瀛楄妭锛夛紙1GB锛?  memory_threshold: 1073741824
  # 鍝嶅簲鏃堕棿闃堝€硷紙绉掞級
  response_threshold: 5.0

# 涓嶅悓涓婁笅鏂囩殑鏄剧ず閰嶇疆
display:
  contexts:
    # 绯荤粺鐘舵€佹樉绀鸿缃?    system:
      standard:
        title: "绯荤粺鐘舵€?
        show_workers: true
        show_alerts: true
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      compact:
        title: "绯荤粺鐘舵€?
        show_workers: false
        show_alerts: false
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      detailed:
        title: "璇︾粏绯荤粺鐘舵€?
        show_workers: true
        show_alerts: true
        show_performance: true
        show_newline_prefix: true
        width: 80
        max_alerts_per_level: 3
    # 鐩戞帶鏄剧ず璁剧疆
    monitoring:
      standard:
        title: "绠￠亾鐩戞帶"
        show_workers: true
        show_alerts: true
        show_performance: true
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      detailed:
        title: "璇︾粏绠￠亾鐩戞帶"
        show_workers: true
        show_alerts: true
        show_performance: true
        show_newline_prefix: true
        width: 80
        max_alerts_per_level: 3
    # 浠诲姟绠＄悊鍣ㄦ樉绀鸿缃?    task:
      standard:
        title: "浠诲姟绠＄悊鍣ㄧ姸鎬?
        show_workers: true
        show_alerts: false
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      compact:
        title: "浠诲姟绠＄悊鍣ㄧ姸鎬?
        show_workers: false
        show_alerts: false
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
    # 搴旂敤绋嬪簭鐘舵€佹樉绀鸿缃?    application:
      standard:
        title: "搴旂敤绋嬪簭鐘舵€?
        show_workers: false
        show_alerts: true
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
      detailed:
        title: "璇︾粏搴旂敤绋嬪簭鐘舵€?
        show_workers: true
        show_alerts: true
        show_performance: true
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3
    # 涓荤姸鎬佹樉绀鸿缃?    main:
      standard:
        title: "绠￠亾鐘舵€?
        show_workers: true
        show_alerts: false
        show_performance: false
        show_newline_prefix: false
        width: 80
        max_alerts_per_level: 3

# 鏁版嵁鎸佷箙鍖栭厤缃?persistence:
  # 淇濆瓨缁撴灉鐨勬壒澶勭悊澶у皬
  batch_size: 50
  # 缁撴灉淇濆瓨闂撮殧锛堢锛?  save_interval: 30
  # 闃熷垪鐘舵€佷繚瀛橀棿闅旓紙绉掞級
  queue_interval: 60
  # 瀹氭湡蹇収闂撮殧锛堢锛?  snapshot_interval: 300
  # 鍚姩鏃惰嚜鍔ㄦ仮澶嶇姸鎬?  auto_restore: true
  # 鍏抽棴瓒呮椂锛堢锛?  shutdown_timeout: 30
  # 杈撳嚭鏍煎紡锛屾敮鎸乼xt鎴杗djson
  format: txt

# 鍔ㄦ€佸伐浣滅嚎绋嬬鐞嗗櫒閰嶇疆
worker:
  # 鍚敤/绂佺敤鍔ㄦ€佸伐浣滅嚎绋嬬鐞?  enabled: true
  # 鏈€灏忓伐浣滅嚎绋嬫暟
  min_workers: 2
  # 鏈€澶у伐浣滅嚎绋嬫暟
  max_workers: 16
  # 鑷姩鎵╁睍鐨勭洰鏍囬槦鍒楀ぇ灏?  target_queue_size: 200
  # 绾跨▼姹犺皟鏁撮棿闅旓紙绉掞級
  adjustment_interval: 5.0
  # 鎵╁鐨勯槦鍒楀ぇ灏忛槇鍊硷紙0.0-1.0锛?  scale_up_threshold: 0.8
  # 缂╁鐨勯槦鍒楀ぇ灏忛槇鍊硷紙0.0-1.0锛?  scale_down_threshold: 0.2
  # 鍚敤宸ヤ綔绾跨▼璋冩暣寤鸿鏃ュ織
  log_recommendations: true

# 鍏ㄥ眬閫熺巼闄愬埗閰嶇疆
ratelimits:
  # GitHub API閫熺巼闄愬埗锛堟洿淇濆畧锛?  github_api:
    # 鍩虹閫熺巼锛堟瘡绉掕姹傛暟锛?    base_rate: 0.15
    # 鏈€澶х獊鍙戝ぇ灏?    burst_limit: 3
    # 鍚敤鑷€傚簲閫熺巼闄愬埗
    adaptive: true
  # GitHub缃戦〉鎶撳彇閫熺巼闄愬埗锛堟洿淇濆畧锛?  github_web:
    # 鍩虹閫熺巼锛堟瘡绉掕姹傛暟锛?    base_rate: 0.5
    # 鏈€澶х獊鍙戝ぇ灏?    burst_limit: 3
    # 鍚敤鑷€傚簲閫熺巼闄愬埗
    adaptive: true

# 鎻愪緵鍟嗕换鍔￠厤缃紙OpenAI 涓?Gemini锛?tasks:
  - name: "openai"                    # 鎻愪緵鍟嗗悕绉?浠诲姟鐨勫敮涓€鏍囪瘑绗?
    enabled: true                     # 鏄惁鍚敤
    provider_type: "openai_like"      # 鍐冲畾楠岃瘉鏂规硶锛坥penai_like銆乤nthropic銆乬emini 绛夛級
    use_api: false                    # 浣跨敤GitHub API杩涜鎼滅储
    # 娴佹按绾块樁娈佃缃?鍚敤/绂佺敤鐗瑰畾鐨勫鐞嗛樁娈?
    stages:
      search: true         # 鍚敤鎼滅储闃舵
      gather: true         # 鍚敤閲囬泦闃舵
      check: true          # 鍚敤楠岃瘉闃舵
      inspect: true        # 鍚敤API鑳藉姏妫€鏌?    # 鐢ㄤ簬瀵嗛挜楠岃瘉鐨凙PI绔偣閰嶇疆
    api:
      base_url: https://api.openai.com
      completion_path: /v1/chat/completions
      model_path: /v1/models          # 楠岃瘉鏇村揩鏇磋交閲?      default_model: gpt-4o-mini
      auth_key: Authorization         # 浠?Bearer <key> 褰㈠紡鍙戦€?      extra_headers:
        User-Agent: "KeyValidator/1.0 (+https://example.com)"
        # OpenAI-Organization: "org_xxx"  # 濡傞渶缁勭粐绾ф牎楠屽彲鍚敤
      api_version: ""                 # OpenAI 鍏叡API鐣欑┖锛汚zure 鍙﹂厤
      timeout: 20                     # 楠岃瘉浼樺厛 /v1/models
      retries: 5                      # 鎻愰珮閲嶈瘯搴斿鐬椂 429/瓒呮椂
    # 妯″紡鍖归厤閰嶇疆
    patterns:
      # 瑕嗙洊甯歌 OpenAI 瀵嗛挜褰㈡€侊紝閬垮厤渚濊禆鐗瑰畾鐗囨瀵艰嚧婕忔姤
      key_pattern: "sk(?:-proj)?-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}"
      address_pattern: ""
      endpoint_pattern: ""
      model_pattern: ""
    # 鎼滅储鏉′欢(鐢ㄤ簬鏌ユ壘娼滃湪瀵嗛挜鐨勬悳绱㈡煡璇?
    conditions:
      - query: '/sk(?:-proj)?-[A-Za-z0-9]{20}T3BlbkFJ[A-Za-z0-9]{20}/'
      - query: 'content:T3BlbkFJ AND (openai OR "api.openai.com")'
      - query: '/sk-[A-Za-z0-9]{48}/ AND (openai OR "api.openai.com")'
      - query: '/sk(?:-proj)?-[A-Za-z0-9]{20}T3BlbkFJ[A-Za-z0-9]{20}/ AND (filename:.env OR path:.env)'
      - query: 'OPENAI_API_KEY AND (filename:.env OR path:.env)'
      - query: 'OPENAI_API_KEY AND (language:Python OR language:JavaScript OR language:TypeScript)'
      - query: '"Authorization: Bearer" AND "api.openai.com"'
      - query: '"api.openai.com/v1" AND (openai OR "Authorization: Bearer")'
      - query: '/sk-[A-Za-z0-9]{48}/ AND (filename:.env OR path:.env)'
      - query: '/sk-[A-Za-z0-9]{48}/ AND (language:Python OR language:TypeScript)'
      - query: 'content:T3BlbkFJ AND (path:config OR path:configs OR path:settings)'
      - query: 'content:T3BlbkFJ AND (filename:config.js OR filename:settings.py)'
      - query: 'OPENAI_API_KEY AND (path:serverless OR path:functions OR path:cloud)'
      - query: 'OPENAI_API_KEY AND (filename:.env.local OR filename:.env.production OR filename:.env.development)'
      - query: '"OPENAI_API_KEY=" AND (filename:.env OR path:.env)'
      - query: '"sk-" AND (openai OR "api.openai.com") AND (filename:.env OR path:.env)'
      - query: '"OpenAI-Organization" AND ("sk-" OR T3BlbkFJ)'
      - query: 'content:T3BlbkFJ AND language:Go'
      - query: 'content:T3BlbkFJ AND language:PHP'
      - query: 'content:T3BlbkFJ AND language:Ruby'
      - query: '"api.openai.com" AND "Bearer sk-"'
      - query: 'openai AND "sk-" AND NOT test'
    # 閫熺巼闄愬埗閰嶇疆锛堟洿绋冲仴鐨勮嚜閫傚簲鍙傛暟锛?    rate_limit:
      base_rate: 1.0           # 绋冲Ε璧锋锛岄厤鍚堥噸璇曚笌鑷€傚簲
      burst_limit: 10
      adaptive: true
      backoff_factor: 0.6      # 绋嶅寮洪€€閬?      recovery_factor: 1.2     # 鎭㈠鐣ュ揩
      max_rate_multiplier: 2.0
      min_rate_multiplier: 0.1
    # 缁撴灉鐩綍(鑷畾涔夎緭鍑虹洰褰?
    extras:
      directory: "openai"

  # OpenAI API-based searches (non-regex queries via GitHub API)
  - name: "openai_api"
    enabled: true
    provider_type: "openai_like"
    use_api: true
    stages:
      search: true
      gather: true
      check: true
      inspect: true
    api:
      base_url: https://api.openai.com
      completion_path: /v1/chat/completions
      model_path: /v1/models
      default_model: gpt-4o-mini
      auth_key: Authorization
      extra_headers: {}
      api_version: ""
      timeout: 30
      retries: 3
    patterns:
      key_pattern: "sk(?:-proj)?-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}"
      address_pattern: ""
      endpoint_pattern: ""
      model_pattern: ""
    conditions:
      - query: 'content:T3BlbkFJ AND (openai OR "api.openai.com")'
      - query: 'OPENAI_API_KEY AND (filename:.env OR path:.env)'
      - query: 'OPENAI_API_KEY AND (language:Python OR language:JavaScript OR language:TypeScript)'
      - query: '"Authorization: Bearer" AND "api.openai.com"'
      - query: '"api.openai.com/v1" AND (openai OR "Authorization: Bearer")'
      - query: 'content:T3BlbkFJ AND (path:config OR path:configs OR path:settings)'
      - query: 'content:T3BlbkFJ AND (filename:config.js OR filename:settings.py)'
      - query: 'OPENAI_API_KEY AND (path:serverless OR path:functions OR path:cloud)'
      - query: 'OPENAI_API_KEY AND (filename:.env.local OR filename:.env.production OR filename:.env.development)'
      - query: '"OPENAI_API_KEY" AND (filename:.env OR path:.env)'
      - query: '"sk-" AND (openai OR "api.openai.com") AND (filename:.env OR path:.env)'
      - query: '"OpenAI-Organization" AND ("sk-" OR T3BlbkFJ)'
      - query: 'content:T3BlbkFJ AND language:Go'
      - query: 'content:T3BlbkFJ AND language:PHP'
      - query: 'content:T3BlbkFJ AND language:Ruby'
      - query: '"api.openai.com" AND "Bearer sk-"'
      - query: 'openai AND "sk-" AND NOT test'
      - query: 'OPENAI_API_KEY AND (filename:settings.json OR filename:settings.py OR filename:application.yml)'
      - query: 'OPENAI_API_KEY AND path:.github/workflows'
      - query: '"api.openai.com" AND (filename:package.json OR filename:package-lock.json)'
      - query: '"api.openai.com" AND language:TypeScript'
      - query: '"api.openai.com" AND language:Python'
      - query: 'openai AND "Bearer" AND (filename:index.js OR filename:api.ts)'
      - query: 'OPENAI_API_KEY AND (path:src OR path:server OR path:backend)'
      - query: 'OPENAI_API_KEY AND (path:examples OR path:samples) NOT test'
      - query: 'OPENAI_API_KEY AND extension:env'
      - query: 'OPENAI_API_KEY AND extension:yaml'
      - query: '"sk-" AND (language:Go OR language:Ruby)'
      - query: '"Authorization" AND "sk-" AND path:config'
      - query: 'openai AND (filename:.npmrc OR filename:.yarnrc)'
      - query: 'openai AND path:docker'
      - query: 'openai AND path:kubernetes'
    rate_limit:
      base_rate: 0.5
      burst_limit: 10
      adaptive: true
      backoff_factor: 0.6
      recovery_factor: 1.2
      max_rate_multiplier: 2.0
      min_rate_multiplier: 0.1
    extras:
      directory: "openai"

  # 鎻愪緵鍟嗗悕绉?浠诲姟鐨勫敮涓€鏍囪瘑绗?
  - name: "gemini"
    # 鏄惁鍚敤
    enabled: true
    # 鍐冲畾楠岃瘉鏂规硶锛坥penai_like銆乤nthropic銆乬emini 绛夛級
    provider_type: "gemini"
    # 浣跨敤GitHub API杩涜鎼滅储
    use_api: false
    # 娴佹按绾块樁娈佃缃?鍚敤/绂佺敤鐗瑰畾鐨勫鐞嗛樁娈?
    stages:
      search: true    # 鍚敤鎼滅储闃舵
      gather: true    # 鍚敤閲囬泦闃舵
      check: true     # 鍚敤楠岃瘉闃舵
      inspect: true   # 鍚敤API鑳藉姏妫€鏌?    # 鐢ㄤ簬瀵嗛挜楠岃瘉鐨凙PI绔偣閰嶇疆锛堟柊澧烇紝渚夸簬蹇€熸牎楠岋級
    api:
      base_url: https://generativelanguage.googleapis.com
      model_path: /v1/models
      completion_path: /v1/models
      default_model: gemini-2.5-pro
      auth_key: x-goog-api-key
      extra_headers:
        User-Agent: "KeyValidator/1.0 (+https://example.com)"
      api_version: ""
      timeout: 20
      retries: 5
    # 璇存槑锛氭湰浠诲姟鍦ㄩ獙璇侀樁娈典細浣跨敤鎼滅储鍒扮殑鍊欓€?key 鍔ㄦ€佽皟鐢?API锛?    # 鍥犳鏃犻渶鍦ㄨ繍琛岀幆澧冧腑鎻愪緵鍥哄畾鐨?GEMINI_API_KEY 鐜鍙橀噺銆?    # 妯″紡鍖归厤閰嶇疆
    patterns:
      # 鏇撮€氱敤鐨?Google/Gemini API Key 褰㈡€?      key_pattern: 'AIzaSy[a-zA-Z0-9_\-]{33}'
    # 鎼滅储鏉′欢(鐢ㄤ簬鏌ユ壘娼滃湪瀵嗛挜鐨勬悳绱㈡煡璇?
    conditions:
      - query: '/AIza[0-9A-Za-z_\-]{35}/ AND (gemini OR generativelanguage.googleapis.com)'
      - query: '/AIzaSy[a-zA-Z0-9_\-]{33}/ AND content:gemini'
      - query: 'GEMINI_API_KEY OR GOOGLE_API_KEY'
      - query: 'GEMINI_API_KEY AND (filename:.env OR path:.env)'
      - query: '"x-goog-api-key" AND (gemini OR generativelanguage.googleapis.com)'
      - query: '"generativelanguage.googleapis.com" AND "AIza"'
      - query: '/AIza[0-9A-Za-z_\-]{35}/ AND (filename:.env OR path:.env)'
      - query: '/AIza[0-9A-Za-z_\-]{35}/ AND (language:JavaScript OR language:Python)'
      - query: '"AIza" AND (filename:config.js OR filename:settings.py)'
      - query: 'GOOGLE_API_KEY AND (filename:.env OR path:.env)'
      - query: '"AIza" AND (path:config OR path:configs OR path:settings)'
      - query: 'content:AIza AND language:Go'
      - query: 'content:AIza AND language:TypeScript'
      - query: '"AIza" AND "gemini" AND NOT sample'
      - query: '"AIza" AND "gemini" AND NOT example'
      - query: '"AIza" AND "gemini" AND NOT test'
      - query: '"AIza" AND (path:serverless OR path:functions)'
      - query: '"AIza" AND (filename:.env.local OR filename:.env.production)'
      - query: 'content:AIza AND (filename:.env OR path:.env)'
      - query: '"x-goog-api-key" AND language:JavaScript'
      - query: '"AIza" AND "GOOGLE_API_KEY"'
      - query: '"AIza" AND "GEMINI_API_KEY"'
    # 閫熺巼闄愬埗閰嶇疆锛堜笌 openai 涓€鑷寸殑鑷€傚簲鍙傛暟闆嗭級
    rate_limit:
      base_rate: 0.5
      burst_limit: 10
      adaptive: true
      backoff_factor: 0.6
      recovery_factor: 1.2
      max_rate_multiplier: 2.0
      min_rate_multiplier: 0.1

