name: Publish Variant Images

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: disable-gemini
            app_config: config.openai.yaml
            tag: 0.1.7
          - name: disable-openai
            app_config: config.gemini.yaml
            tag: 0.1.9
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            APP_CONFIG=${{ matrix.app_config }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/nianmodaye:${{ matrix.tag }}

