name: Publish Variant Images

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write

env:
  # GHCR requires lowercase owner/repo in image references
  OWNER_LC: ${{ toLower(github.repository_owner) }}

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: disable-gemini
            app_config: config.openai.yaml
            tag: 0.1.7
          - name: disable-openai
            app_config: config.gemini.yaml
            tag: 0.1.9
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64
          build-args: |
            APP_CONFIG=${{ matrix.app_config }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/nianmodaye:${{ matrix.tag }}
